{% set name = "ws4py" %}
{% set version = "0.4.3" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "ee12b58384bab8bfdcd1c76dcd6852047aec163af17175fc0f73e255d107dd7a" %}
{% set build = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - ws4py
    - ws4py.client
    - ws4py.server

about:
  home: https://github.com/Lawouach/WebSocket-for-Python
  # No MANIFEST - see https://github.com/Lawouach/WebSocket-for-Python/pull/215
  license_file:  {{ RECIPE_DIR }}/LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'WebSocket client and server library for Python 2, 3, and PyPy'
  dev_url: https://github.com/Lawouach/WebSocket-for-Python
  doc_url: https://ws4py.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
