{% set version = "0.3.2" %}

package:
  name: ws4py
  version: {{ version }}

source:
  fn: ws4py-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/w/ws4py/ws4py-{{ version }}.tar.gz
  sha256: 503370e86fe7a4d74ba2b7f9df00e129d8558c22fc0a452e8f81d003a5421e0e

build:

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - ws4py
    - ws4py.client
    - ws4py.server

about:
  home: https://github.com/Lawouach/WebSocket-for-Python
  license: BSD 3-Clause
  summary: 'WebSocket client and server library for Python 2, 3, and PyPy'

extra:
  recipe-maintainers:
    - pmlandwehr
