{% set name = "ws4py" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f87b19b773f0a0744a38f3afa36a803286dd3197f0bb35d9b75293ec7002d19

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-cache-dir

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - test
  imports:
    - ws4py
    - ws4py.client
    - ws4py.server
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v test
  requires:
    - pip
    - pytest
    - cherrypy

about:
  home: https://github.com/Lawouach/WebSocket-for-Python
  license_file:  LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: ws4py is a Python package implementing the WebSocket protocol as defined in RFC 6455.
  description: |
    ws4py is a Python package implementing the WebSocket protocol as defined in RFC 6455.
    It comes with various server and client implementations and runs on CPython 2/3, PyPy and Android.
  dev_url: https://github.com/Lawouach/WebSocket-for-Python
  doc_url: https://ws4py.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
