# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "MSedvS8OOPaAr9RYfU8Ov1ycl/4yoEzNLNSWAHQOx9WXNLqryx7/COtNDVWWIYLbKu83uasmpyN3cDVyIhuZu3pjuqGJmUrdaFCpXQ9MvxIpgdqNZI7hAlftpGP1XKcQUDAtlVlvVbfBESq9doFyb2jKF5xHoDQ3bzzy9JorkiaPmdx/beBWrgpitAu+cc8O+N+TQLBYlQG+6Dty3R+nQ/nFP8X8M6N35LOPG/l9tXkAxW9imXYulF/ekBjSAGc0M6hYTcZbqlnZa/SNa/pxNGiEGA/yLSIDOJagnwIYBxFQ9S0UB21x0WlQKXrJyoOMU3L6lR9XR5Q8FNxp1ao5jHn0Cg1SV2gsYP8134YQ6xAMs7L+POeYbH42r8Lw8CZvVvIZNEPumzaLL3wrKK/GUwYL36UtfBIpH5yUmofb69C1JJYce1tfFUecC/dJOrg/ultGVwBgnR7cjCE4Q8LFJ7dQv4rQLiQqKEgdhgjEAkyT/fHsoUtt7QJz/36CUe4A3U/ivFGfudJ9o3fN0K+pNte9m2E3Tx+/9fsxptgQV0fsy5Hy183YaHIdyevi3g9X1AOhuuhYHJdgE8fEcV8VT5u8t86fNwo6q6DajOyH3W3neLftJaYWyrGn6EjmKtsmDH43JSlIwnUSQQLepQoLyUPxcSP7WgzKO20S6NbZv+4="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
