travis:
  secure:
    BINSTAR_TOKEN: MSedvS8OOPaAr9RYfU8Ov1ycl/4yoEzNLNSWAHQOx9WXNLqryx7/COtNDVWWIYLbKu83uasmpyN3cDVyIhuZu3pjuqGJmUrdaFCpXQ9MvxIpgdqNZI7hAlftpGP1XKcQUDAtlVlvVbfBESq9doFyb2jKF5xHoDQ3bzzy9JorkiaPmdx/beBWrgpitAu+cc8O+N+TQLBYlQG+6Dty3R+nQ/nFP8X8M6N35LOPG/l9tXkAxW9imXYulF/ekBjSAGc0M6hYTcZbqlnZa/SNa/pxNGiEGA/yLSIDOJagnwIYBxFQ9S0UB21x0WlQKXrJyoOMU3L6lR9XR5Q8FNxp1ao5jHn0Cg1SV2gsYP8134YQ6xAMs7L+POeYbH42r8Lw8CZvVvIZNEPumzaLL3wrKK/GUwYL36UtfBIpH5yUmofb69C1JJYce1tfFUecC/dJOrg/ultGVwBgnR7cjCE4Q8LFJ7dQv4rQLiQqKEgdhgjEAkyT/fHsoUtt7QJz/36CUe4A3U/ivFGfudJ9o3fN0K+pNte9m2E3Tx+/9fsxptgQV0fsy5Hy183YaHIdyevi3g9X1AOhuuhYHJdgE8fEcV8VT5u8t86fNwo6q6DajOyH3W3neLftJaYWyrGn6EjmKtsmDH43JSlIwnUSQQLepQoLyUPxcSP7WgzKO20S6NbZv+4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
