travis:
  secure:
    BINSTAR_TOKEN: hasE9RcCFAf0m2lKQ71OPYh94Vr83PVoP8C2vylifiDXCtokXHyihK9gl9vuMxfu6XU6HhtRzmY3yXPBvnChmomv5i0fCepW+Djo3xf5HAVRvb0wAELEOWpPRP3adzEPgLWMzV8FQ1B5gx9WKUQhIqZtuh172VONa0KysTfKkjvbS2h/HJ6/XSLo+Q1Jh/g1/1I0NTjrD1kxey5vKFGVfLEI79xgPAKdGHe7L5LvcQi/xXPv2JiMTbUxhVA6143cXSJYst4kCK1Syopi0W9NkC8lKl9lLxqHumgUWmxAONKNbIJVpOX/j2eg3iZRKr4bxPrRvFfJlMiZWz2wFkQaK1jjSkOs4UPfoOyuXWz/fZwR2nIWt2XcJHE0DGqK4C0UYghkJAGGUj9V331NykUceHJYAsvh4XE+BsHH0369YOuUi+bONBPsDTNuapcyWVzjupYpgRqFGV2sBAQ/TY4B5qGChuGhXdtUMsiQYzd/prsU9JZhLIs+pklGHfuzfX+hi5w0UHNawXrumu0c2dTxuX29kWxIHJdx8vC5BCl38NvwapCTT5qhvNxibsAGaK3eCgJwhmiQQfh+Ie9DUXMtoR/oM1E/Oo2lOoYtACtAKEgxh5YHa5ldtw7PYVxn7Zct19Ul6+hxFAGo/eAGBmw94i2NrgbCD9IwO8960cdE0yQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
